name: Deploy to WAMP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull latest changes in WAMP directory
        run: |
          cd C:\wamp64\www\UPJ-RPC\
          git pull origin main
          
